### ISSUE TITLE
client.framebuffer error

### ISSUE THREAD

**Issue by mizhdi** [openstf/adbkit#104]
```
TypeError: Cannot read property 'pipe' of undefined
    at FrameBufferCommand._convert (/Users/sean/Repo/Koto/kotohime-executive-service/node_modules/adbkit/lib/adb/command/host-transport/framebuffer.js:67:9)
    at /Users/sean/Repo/Koto/kotohime-executive-service/node_modules/adbkit/lib/adb/command/host-transport/framebuffer.js:39:34
From previous event:
    at /Users/sean/Repo/Koto/kotohime-executive-service/node_modules/adbkit/lib/adb/command/host-transport/framebuffer.js:30:47
From previous event:
    at FrameBufferCommand.execute (/Users/sean/Repo/Koto/kotohime-executive-service/node_modules/adbkit/lib/adb/command/host-transport/framebuffer.js:26:37)
    at /Users/sean/Repo/Koto/kotohime-executive-service/node_modules/adbkit/lib/adb/client.js:317:48
    at processImmediate (timers.js:632:19)
From previous event:
    at Client.framebuffer (/Users/sean/Repo/Koto/kotohime-executive-service/node_modules/adbkit/lib/adb/client.js:316:35)
    at Promise (/Users/sean/Repo/Koto/kotohime-executive-service/app/util/help.js:92:12)
    at new Promise (<anonymous>)
    at Object.help.screencap (/Users/sean/Repo/Koto/kotohime-executive-service/app/util/help.js:91:10)
    at DefaultController.device (/Users/sean/Repo/Koto/kotohime-executive-service/app/io/controller/default.js:90:10)
    at Object.callFn (/Users/sean/Repo/Koto/kotohime-executive-service/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/sean/Repo/Koto/kotohime-executive-service/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Socket.socket.on.args (/Users/sean/Repo/Koto/kotohime-executive-service/node_modules/egg-socket.io/lib/io.js:104:23)
    at Socket.emit (events.js:182:13)
    at /Users/sean/Repo/Koto/kotohime-executive-service/node_modules/socket.io/lib/socket.js:528:12
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
```

**Comment by frappexx** [comment]
the same error occurs and I found that  parameter was missing in FrameBufferCommand.execute() when it calls FrameBufferCommand._convert(serial,format,raw) (/lib/adb/command/host-transport/framebuffer.js). With a modification of  line39: `stream=_this._convert(meta,format)` to  `stream=_this._convert(meta,format,_this.parser.raw())`  ,the program works.
