### ISSUE TITLE
unplugin mobile cause crash

### ISSUE THREAD

**Issue by minghong** [openstf/adbkit#37]
some times when I unplug a mobile from Usb cable, stf is crashed. Here is log:
device:support:push 21886 [13a1a8cf] Sending output to "tcp://127.0.0.1:7116"
device 21886 [13a1a8cf] Preparing device
device:support:sub 21886 [13a1a8cf] Receiving input from "tcp://127.0.0.1:7114"
device:support:sub 21886 [13a1a8cf] Subscribing to permanent channel "*ALL"
device 21886 [13a1a8cf] Setup had an error FailError: Failure: 'device not found'
    at /stf/node_modules/adbkit/lib/adb/parser.js:226:31
From previous event:
    at Parser.readError (/stf/node_modules/adbkit/lib/adb/parser.js:225:31)
    at /stf/node_modules/adbkit/lib/adb/command/host/transport.js:25:35
From previous event:
    at HostTransportCommand.execute (/stf/node_modules/adbkit/lib/adb/command/host/transport.js:19:39)
    at /stf/node_modules/adbkit/lib/adb/client.js:257:47
    at processImmediate [as _immediateCallback](timers.js:367:17)
From previous event:
    at Client.transport (/stf/node_modules/adbkit/lib/adb/client.js:256:32)
    at Client.waitBootComplete (/stf/node_modules/adbkit/lib/adb/client.js:531:19)
    at ensureBootComplete (/stf/lib/units/device/support/adb.js:19:15)
    at /stf/lib/units/device/support/adb.js:28:12
    at SerialSyrup.ParallelSyrup.invoke (/stf/node_modules/stf-syrup/lib/parallel.js:54:24)
    at /stf/node_modules/stf-syrup/lib/serial.js:43:33
    at process._tickCallback (node.js:355:11)

**Comment by sorccu** [comment]
This issue is old, but it wasn't really an adbkit issue anyway. If adbkit returns an error, that's correct. It's stf that may not have been handling it correctly at the time (unsure if it does now).

Closing.
