### ISSUE TITLE
client.openProcStat(serial[, callback]) Android 7

### ISSUE THREAD

**Issue by anaraquelazevedo** [openstf/adbkit#66]
I´m having a problem accessing the data in some mobiles models, with android 7 (for instance, nexus 6). With android 7 i cannot access the system files, proc/stat for example, and since adbkit´s method client.openProcStat(serial[, callback]) tries to read that data. I can´t garantee an appropriate error handling while acessing that data and i get this error:

Unhandled rejection FailError: Failure: open failed: Permission denied'
    at /stf/node_modules/adbkit/lib/adb/sync.js:305:33
    at tryCatcher (/stf/node_modules/adbkit/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/stf/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/stf/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/stf/node_modules/adbkit/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/stf/node_modules/adbkit/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/stf/node_modules/adbkit/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/stf/node_modules/adbkit/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

 Can anyone shoot any ideas? or new aproaches to this problem!? Thanx in advance!

**Comment by sorccu** [comment]
Run `adb shell cat /proc/stat`. If that gives you permission denied, then there isn't anything we can do about it. You could possibly use `dumpsys` with `.shell()` to access similar information.

**Comment by anaraquelazevedo** [comment]
with adb shell cat /proc/stat i have permission to access file! 
How can I make this method for all phones with adb shell?

**Comment by sorccu** [comment]
Hmmm that's weird... what's the model? Run `adb devices -l` and paste the line here (you can remove the serial number though if you like).

**Comment by anaraquelazevedo** [comment]
List of devices attached 
##########             device usb:1-2 product:shamu model:Nexus_6 device:shamu

**Comment by pnagele** [comment]
Hi,
got the same problem that openProcStat fails with permission denied, while I can access proc/stat without any problems.

XXXXXXXXXXX       device usb:336592896X product:LON-L29 model:LON_L29 device:HWLON

(Huawei Mate 9  Pro)
