### ISSUE TITLE
adbkit.openLogcat has a bug at android 7.0

### ISSUE THREAD

**Issue by 0x88l** [openstf/adbkit#68]
Some Android7.0 like "huawei Mate 9" when use adbkit.openlogcat was err like the log:

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Unprocessable entry data 'ket name[Listener] fd['
    at Binary._processEntry (d:\webstorm\test\node_modules\adbkit-logcat\lib\logcat\parser\binary.js:85:26)
    at Binary.parse (d:\webstorm\test\node_modules\adbkit-logcat\lib\logcat\parser\binary.js:56:14)
    at LineTransform.<anonymous> (d:\webstorm\test\node_modules\adbkit-logcat\lib\logcat\reader.js:90:33)
    at emitOne (events.js:77:13)
    at LineTransform.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at LineTransform.Readable.push (_stream_readable.js:111:10)
    at LineTransform.Transform.push (_stream_transform.js:128:32)
    at LineTransform._transform (d:\webstorm\test\node_modules\adbkit\lib\adb\linetransform.js:42:12)
    at LineTransform.Transform._read (_stream_transform.js:167:10)
    at LineTransform.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
    at LineTransform.Writable.write (_stream_writable.js:214:11)
    at Socket.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:77:13)

I have found the problem at  adbkit-logcat/src/logcat/parser/binary.coffee
![image](https://cloud.githubusercontent.com/assets/18346467/24388486/9dc2b41e-13ad-11e7-9459-18c535b0d36b.png)

When occured err that 'data.length' was eq 0.
This problem not often happen. It maybe occurs when running monkey test.
I try to modify this file like this:

_processEntry: (entry, data) ->
    entry.setPriority data[0]
    cursor = 1
    length = data.length
++    if length < cursor
      cursor += 1
      return
++  else
      while cursor < length
        if data[cursor] is 0
          entry.setTag data.slice(1, cursor).toString()
          entry.setMessage data.slice(cursor + 1, length - 1).toString()
          @emit 'entry', entry
          return
        cursor += 1
      @emit 'error', new Error "Unprocessable entry data '#{data}'"
      return

**Comment by sorccu** [comment]
Are you sure you're using the latest version?

**Comment by sorccu** [comment]
If yes, then it might be because of the line transform. There was a related
fix a while ago but I don't think it applied to logcat. Not sure right now.

**Comment by 0x88l** [comment]
Yes. I use the newest version.

**Comment by sorccu** [comment]
you said there are other phones too. Do you have a list?

**Comment by 0x88l** [comment]
Wait for some hours please.I try to get the phone list.

**Comment by 0x88l** [comment]
All of Android 7.0 in my hand has this problem
1.LG NEXUS
2.HuaweiMate9
3.HuaweiV9
4.nokia6

**Comment by sorccu** [comment]
Can you do 'npm ls' just in case?

**Comment by 0x88l** [comment]
![image](https://cloud.githubusercontent.com/assets/18346467/24448255/27f4944c-14a6-11e7-9b6c-0821e9bfbb71.png)

**Comment by sorccu** [comment]
Should be fixed now. Could you pull master and try again?

**Comment by sorccu** [comment]
I'm not sure. After a while, I got an error again. Reopening.

**Comment by sorccu** [comment]
Ok I had a big mistake in there. Try now with 2.8.1 and let me know if it works for you.

**Comment by sorccu** [comment]
So is this working now with the latest version?

**Comment by sorccu** [comment]
I’m going to assume this was fixed since there has been no feedback.
